spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.147.128:3306/ich
    username: root
    password: Mysql@123
  redis:
    host: 192.168.147.128
    port: 6379 #Redis服务器连接端口
    timeout: 30000 #连接超时时间（毫秒）
    password: Redis@123
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      static-locations: file:D:\\document\\Vue\\code\\ck-file # E:\\ck-file 文件下的文件可直接通过项目服务地址直接访问
  servlet:
    multipart:
      enabled: true
      max-request-size: 1MB # 最大请求文件的大小
      max-file-size: 1MB # 设置单个文件最大长度
server:
  port: 18081
  servlet:
    context-path: /ich-notes
mybatis-flex:
  mapper-locations: mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ich.note.pojo